### ISSUE TITLE
startup errors after installation

### ISSUE THREAD

**Issue by daslicht** [azat-co/mongoui#20]
Hello,
I did the following:
git clone git@github.com:azat-co/mongoui
npm install
Copy config_default.json file as config.json
node index.js

I get:

```
daslicht@vps58220:~/mongoui$ node index.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'connect/lib/middleware/session/cookie'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/daslicht/mongoui/node_modules/derby/node_modules/racer/lib/session/session.Store.js:2:14)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/daslicht/mongoui/node_modules/derby/node_modules/racer/lib/session/index.js:1:80)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at plugin (/home/daslicht/mongoui/node_modules/derby/node_modules/racer/lib/racer.server.js:123:10)
  at EventEmitter.module.exports.use (/home/daslicht/mongoui/node_modules/derby/node_modules/racer/lib/plugin.js:41:7)
  at Object.<anonymous> (/home/daslicht/mongoui/node_modules/derby/node_modules/racer/lib/racer.js:31:9)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/daslicht/mongoui/node_modules/derby/lib/derby.js:1:75)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/daslicht/mongoui/index.js:23:13)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:902:3

daslicht@vps58220:~/mongoui$ 
```

What am I missing ?

**Comment by bmlyon** [comment]
Thanks for the response about installing without using NPM, that worked for me.

**Comment by azat-co** [comment]
Yes, I need to look into shrinkwrap for npm

**Comment by rex2002xp** [comment]
Excellent , without npm all fine.
