### ISSUE TITLE
Failed at the mongoui@3.1.3 start script 'node node_modules/nodemon/bin/nodemon.js index.js'.

### ISSUE THREAD

**Issue by MostHated** [azat-co/mongoui#41]
Hello, 
    I am having an issue with Mongoui, I cannot seem to get it started up. Do see below my error message from the npm log, I am not quite sure what is going on though. I have apt-get upgraded my npm and have nodejs installed, I also symlinked nodejs to node, etc on Ubuntu 16. Any help would be appreciate!

Thanks,

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mongoui@3.1.3~prestart: mongoui@3.1.3
6 silly lifecycle mongoui@3.1.3~prestart: no script for prestart, continuing
7 info lifecycle mongoui@3.1.3~start: mongoui@3.1.3
8 verbose lifecycle mongoui@3.1.3~start: unsafe-perm in lifecycle true
9 verbose lifecycle mongoui@3.1.3~start: PATH: /usr/share/npm/bin/node-gyp-bin:/usr/local/lib/node_modules/mongoui/node_modules/.bin:/usr/local/lib/node_modules/.bin:/root/bin:/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle mongoui@3.1.3~start: CWD: /usr/local/lib/node_modules/mongoui
11 silly lifecycle mongoui@3.1.3~start: Args: [ '-c', 'node node_modules/nodemon/bin/nodemon.js index.js' ]
12 silly lifecycle mongoui@3.1.3~start: Returned: code: 1  signal: null
13 info lifecycle mongoui@3.1.3~start: Failed to exec start script
14 verbose stack Error: mongoui@3.1.3 start: `node node_modules/nodemon/bin/nodemon.js index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid mongoui@3.1.3
16 verbose cwd /usr/local/lib/node_modules/mongoui
17 error Linux 4.4.0-36-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error mongoui@3.1.3 start: `node node_modules/nodemon/bin/nodemon.js index.js`
22 error Exit status 1
23 error Failed at the mongoui@3.1.3 start script 'node node_modules/nodemon/bin/nodemon.js index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the mongoui package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node node_modules/nodemon/bin/nodemon.js index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs mongoui
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls mongoui
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]`

**Comment by azat-co** [comment]
@MostHated could you try now? the latest 4.1. I did some changes to shrinkwrap which were cause issues before
