### ISSUE TITLE
Global installation does not work

### ISSUE THREAD

**Issue by danielo515** [azat-co/mongoui#48]
Hello,

Thanks for this great tool. However, if you try to install it using the global option it does not work

 1. npm i -g mongoui
 1. mongoui

```
module.js:472
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/mongoui/index.js:6:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

Could you please take a look?

node version: v7.4.0
OS: mac osx el capitan

If you try to install express, then what fails is body-parser, then compression, then express-handlebars... I don't understand why, seems the dependencies on the package.json are correct.

Thanks and regards

**Comment by BioK03** [comment]
Hello,

I observed the same thing on Ubuntu 16.04 LTS with node 6.10.2 installed.

I have installed express (with Express Generator) and mongoose before trying to install MongoUI globally.
It doesn't work with global, local and save installations.

Thanks in advance 😃

**Comment by azat-co** [comment]
@BioK03 @danielo515 please install and check 4.0.6 now. I fixed it by removing shrinkwrap. for some reason new npm started to use shrinkwrap but before npm just used package.json. the shrinkwrap didn't have all the dependencies.
